### ISSUE TITLE
測試環境 C2C  統一超商，找不到文件提供的店號 991182 "0|門市不存在，請重新選擇取貨門市"

### ISSUE THREAD

**Issue by markku636** [ECPay/Logistic_Net#2]
![image](https://user-images.githubusercontent.com/8486599/146681007-06ef8654-bdb8-44fe-a307-ad2dc67df4b3.png)

![image](https://user-images.githubusercontent.com/8486599/146681008-0330c8da-8b2e-4477-a0f0-adffc8bf4156.png)

**Comment by AllennChang** [comment]
您好,感謝您的反應,  測試環境的超商門市調整, 更新如下
測試環境請使用以下門市進行測試，
7-ELEVEN 超商：131386
7-ELEVEN 超商冷凍店取：896539
全家：006598
OK：1328
文件將於近日更新, 造成您的不便, 深感抱歉,

**Comment by markku636** [comment]
可以使用了，感謝
